language: python
os: linux
jobs:
  include:
    - language: python
      python: "3.7"
      install:
        - pip install -r requirements_dev.txt
      script:
        - flake8
        - sudo apt-get update
        - coverage run --source=./app -m pytest
      after_success:
        - coveralls
